.MODEL SMALL
OUTPUT MACRO MSG
    LEA DX,MSG
    MOV AH,09H
    INT 21H
    ENDM
 DISPL MACRO MSGA
    LEA DX,MSGA
    MOV AH,02H
    INT 21H
    ENDM
 INPUT MACRO 
    MOV AH,01H
    INT 21H
    ENDM
 .DATA 
    MSG1 DB 10,13,"ENTER THE NUMBER $",10,13
    MSG2 DB 10,13," THE FACTORIAL OF NUMBER IS : $",10,13 
    N DB ?
    FACT DW ?
    TEMP DB ? 
    D DW ?
 .CODE
    MOV AX,@DATA
    MOV DS,AX
    XOR AX,AX
    XOR CX,CX 
    XOR DX,DX
    OUTPUT MSG1
    INPUT
    MOV N,AL  
    SUB AL,30h
    MOV CL,AL
    XOR AX,AX
    MOV AL,01H
TOP:MUL CX
    LOOP TOP  
    ADD AL,30H 
    MOV TEMP,AL  
    OUTPUT MSG2  
    XOR AX,AX
    MOV AL,TEMP 
    MOV AH,02H 
    MOV DL,TEMP
    INT 21H 
    MOV AH,4CH
    INT 21H
 END